version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5    
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  token_service:
    build: .
    container_name: token_service
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MIGRATION_FILE_PATH : ${MIGRATION_FILE_PATH}
      SERVER_HOST : ${SERVER_HOST}
      SERVER_PORT : ${SERVER_PORT}
      TOKEN_LENGTH : ${TOKEN_LENGTH}
      TOKEN_EXPIRATION_DURATION : ${TOKEN_EXPIRATION_DURATION}
      TOKEN_ACTIVE_DURATION : ${TOKEN_ACTIVE_DURATION}
    depends_on:
      - db
    volumes:
      - ./db/migrations:/app/db/migrations  
    ports:
      - "3000:3000"

volumes:
  postgres_data:
